In [200]:
import sys
sys.path.append("../../")
from utils import *

np.random.seed(0)
c = [custom[0], custom[-1]]

In [240]:
n0, n1 = 1000, 1000
mu = np.array([[0, -2], [0, 2]])
cov = np.array([[[.2, 0], [0, .2]], [[.2, 0], [0, .2]]])

X = np.r_[np.random.multivariate_normal(mu[0], cov[0], n0),
          np.random.multivariate_normal(mu[1], cov[1], n1)]
y = np.r_[[-1]*n0, [1]*n1]

fig = go.Figure([
    go.Scatter(x = X[:,0], y=X[:, 1], mode = 'markers', marker = dict(color=y, colorscale=c, reversescale=True, size = 3)),
    go.Histogram(x = X[y==-1, 0], histnorm="probability density", yaxis = 'y2', opacity = .5, marker = dict(color = c[1][1])),
    go.Histogram(x = X[y==1, 0], histnorm="probability density", yaxis = 'y2', opacity = .5, marker = dict(color = c[0][1])),
    go.Histogram(y = X[y==-1, 1], histnorm="probability density", xaxis = 'x2', opacity = .5, marker = dict(color = c[1][1])),
    go.Histogram(y = X[y==1, 1], histnorm="probability density", xaxis = 'x2', opacity = .5, marker = dict(color = c[0][1]))
    ], layout=go.Layout(
    xaxis =  dict(zeroline = False, domain = [0,0.85], showgrid = False),
    yaxis =  dict(zeroline = False, domain = [0,0.85], showgrid = False),
    xaxis2 = dict(zeroline = False, domain = [0.85,1], showgrid = False),
    yaxis2 = dict(zeroline = False, domain = [0.85,1], showgrid = False),
    hovermode = 'closest', showlegend = False, height=600, width=600,
    title = r"$(1)\text{ Dataset To Fit Perceptron Model To}$"
))

fig.show()

In [241]:
class Perceptron():
    def __init__(self):
        pass
    
    def fit(self,X,y):
        w = np.zeros(1+X.shape[1])
        w[0] = 1
        X = np.column_stack((np.ones(X.shape[0]),X))
        exists_y_i = True
        tmp = X.dot(w.T)
        while exists_y_i:
            tmp = y*np.inner(X,w)
            for i, val in enumerate(tmp):
                if val <= 0:
                    # update w
                    w = w + y[i]*X[i]
                    tmp = X.dot(w.T)
                    continue
                # else all i's hold y[i]*np.inner(X[i],w) > 0
                exists_y_i = False
        return w
    
    def predict(self,X):
        pass
    
    def score(self,X,y):
        pass

In [242]:
print(X)
print(y)
print(w)


[[ 0.19435727 -2.80828829]
 [ 0.85656383 -2.46749209]
 [ 0.07416742 -1.93590411]
 ...
 [-0.14547082  1.53417782]
 [-0.10489412  2.40316497]
 [ 0.20608775  1.84349676]]
[-1 -1 -1 ...  1  1  1]
[-999.         2011.17765268 1994.51993895]


In [243]:
p = Perceptron()
w = res = p.fit(X,y)
intercept = w[0]

lim = np.array([X.min(axis=0), X.max(axis=0)]).T + np.array([-.5,.5])

yy = (-w[1] / w[2]) * lim[0] + (intercept / w[2])

fig.add_trace(go.Scatter(
    line=dict(color="black", width=1),
    x = lim[0],
    y= yy,
    mode = 'lines',
    name = 'growth_factor'
))
print(w)
print(lim[0])
print(yy)
# print(lim)
fig.show()

[-999.           -2.2541243  1998.11687619]
[-1.97380658  2.21398193]
[-0.50219745 -0.49747311]


In [246]:
from sklearn.svm import SVC

class SVM():
    def __init__(self):
        self._svm = SVC(C=1e10, kernel="linear")
        
    def fit(self,X,y):
        self._svm = self._svm.fit(X,y)
        print(self._svm.get_params())
    
    def predict(self,X):
        return self._svm.predict(X)
    
    def score(self,X,y):
        pass
    

In [247]:
svm = SVM()
print(svm.fit(X,y))
print(svm.predict(X) == y)

{'C': 10000000000.0, 'break_ties': False, 'cache_size': 200, 'class_weight': None, 'coef0': 0.0, 'decision_function_shape': 'ovr', 'degree': 3, 'gamma': 'scale', 'kernel': 'linear', 'max_iter': -1, 'probability': False, 'random_state': None, 'shrinking': True, 'tol': 0.001, 'verbose': False}
None
[ True  True  True ...  True  True  True]


In [255]:
from sklearn.linear_model import LogisticRegression
class Logistic():
    def __init__(self):
        self._logistic = LogisticRegression(solver="liblinear")
     
    def fit(self,X,y):
        self._logistic = self._logistic.fit(X,y)
        print(self._logistic.get_params())
         
    def predict(self,X):
        return self._logistic.predict(X)
    
    def score(self,X,y):
        pass

In [256]:
lg = Logistic()
print(lg.fit(X,y))
print(lg.predict(X) == y)

{'C': 1.0, 'class_weight': None, 'dual': False, 'fit_intercept': True, 'intercept_scaling': 1, 'l1_ratio': None, 'max_iter': 100, 'multi_class': 'auto', 'n_jobs': None, 'penalty': 'l2', 'random_state': None, 'solver': 'liblinear', 'tol': 0.0001, 'verbose': 0, 'warm_start': False}
None
[ True  True  True ...  True  True  True]
